name: Azure CLI Practice

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  practice-az-commands:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out your repository code

    - name: Install Azure CLI
      run: |
        # Install Azure CLI on the runner
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Run basic Azure CLI commands
      run: |
        # Display Azure CLI version (no authentication required)
        az --version

        # Simulate a command that doesn't require authentication
        echo "This is a practice command. No real Azure credentials are needed."

        # Example: List locations (requires authentication, but will fail gracefully)
        echo "Attempting to list Azure locations (will fail without credentials):"
        az account list-locations --output table || echo "This command failed because no credentials were provided."
