name: azure-cli
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_REGISTRY_URL }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
 
    - name: Build and push Docker image
      run: |
        IMAGE_NAME=${{ secrets.AZURE_REGISTRY_URL }}/niginx
        IMAGE_TAG=v1
 
        echo "Building Docker image..."
        docker build -t $IMAGE_NAME:$IMAGE_TAG -f nginx.dockerFile .
 
        echo "Pushing Docker image to ACR..."
        docker push $IMAGE_NAME:$IMAGE_TAG
 
    - name: Logout from Azure Container Registry
      run: docker logout ${{ secrets.AZURE_REGISTRY_URL }}
